### ISSUE TITLE
Container override not referencing correct task definition container

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data-airflow#119]
## What

When running an ingest in the dev MWAA, the `veda_ingest_raster` DAG fails at the `build_stac` process. The error shown is:

`An error occurred (InvalidParameterException) when calling the RunTask operation: Override for container named veda-pipeline-dev-veda-build_stac is not a container in the TaskDefinition.`

This error is because the DAG files being uploaded to s3 does not align with the task definition container name in ECS. This may be a result of the way the MWAA module [DAG upload to s3](https://github.com/NASA-IMPACT/mwaa_tf_module/blob/ae92d997a76f237972c5a7a265f8636cf53b2964/platform/s3_bucket/main.tf#L60) is triggered.
## Acceptance Criteria

- [ ] The `veda_ingest_raster` DAG is able to run without errors and changes to the DAG triggers an upload to the s3 bucket.

**Comment by smohiudd** [comment]
Log to airflow failure: https://4e76fa52-1de6-41a5-b364-691fb1cc69f4.c18.us-west-2.airflow.amazonaws.com/log?dag_id=veda_ingest_raster&task_id=Process.build_stac&execution_date=2024-03-11T19%3A53%3A24.694973%2B00%3A00

**Comment by amarouane-ABDELHAK** [comment]
The synchronization of DAGs from the S3 bucket to MWAA was not happening because the bucket did not block all public access. Once the public access was blocked, the DAGs synchronized, and the build_stac executed successfully.

**Comment by smohiudd** [comment]
@amarouane-ABDELHAK we're getting the same error now in the production instance in MCP:

```
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the RunTask operation: Override for container named data-pipeline-production-veda-build_stac is not a container in the TaskDefinition.
```

Right now we're using mwaa module v1.1.7.0. Should we try https://github.com/NASA-IMPACT/mwaa_tf_module/releases/tag/v1.1.8 and see if we're getting the same issue?

**Comment by amarouane-ABDELHAK** [comment]
The root terraform module of MWAA we were using  uses `aws s3 sync` with the flag size-only which will update teh DAG files during pull requests while disregarding any discrepancies between the current state of  the DAGs files in the file system (of the node executing GitHub CI) and the S3 DAGs folder. A recent pull request was approved to synchronize files without this flag. The release can be found [here](https://github.com/NASA-IMPACT/mwaa_tf_module/releases/tag/v1.1.9)
