### ISSUE TITLE
Test environment SM2A deployment for VEDA

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data-airflow#135]
## What

The existing veda MWAA will eventually be deployed as a self managed airflow service (aka SM2A). This will offer stability, speed and additional features compared to AWS MWAA. Before the SM2A can be deployed, exiting task definition DAGs must be reconfigured/ 

## PI Objective

[Objective 3: Improve Ingestion Workflows ](https://github.com/NASA-IMPACT/veda-architecture/issues/407)

## Acceptance Criteria

- [x] Reconfigured task definitions are reviewed by the team
- [x] Test SM2A is deployed in UAH

**Comment by smohiudd** [comment]
Repo for self managed airflow: https://github.com/NASA-IMPACT/veda-self-managed-airflow

**Comment by smohiudd** [comment]
Team reviewed the SM2A task definitions on April 9 team sync.

**Comment by amarouane-ABDELHAK** [comment]
Task definitions are defined here
- [Workers](https://github.com/NASA-IMPACT/self-managed-apache-airflow/blob/main/infrastructure/ecs_services/airflow_worker.tf#L9) 
- [Scheduler](https://github.com/NASA-IMPACT/self-managed-apache-airflow/blob/main/infrastructure/ecs_services/airflow_scheduler.tf#L39)
- [Webserver](https://github.com/NASA-IMPACT/self-managed-apache-airflow/blob/main/infrastructure/ecs_services/airflow_server.tf#L9)
- [Metrics](https://github.com/NASA-IMPACT/self-managed-apache-airflow/blob/main/infrastructure/ecs_services/airflow_metrics.tf#L23)
The architecture of SM2A can be found [here](https://github.com/NASA-IMPACT/self-managed-apache-airflow/tree/main?tab=readme-ov-file#self-managed-apache-airflow-sm2a-design-document)
