### ISSUE TITLE
Cognito landing page errors

### ISSUE THREAD

**Issue by ividito** [NASA-IMPACT/veda-data-airflow#170]
In production, when attempting to authorize through the docs page, I get redirected to a Cognito error page at `https://veda-auth-stack-production.auth.us-west-2.amazoncognito.com/error?error=Required+parameters+missing`. There might be a missing configuration value, but I can't figure out what it might be.

The same flow on the ingest API, which uses the same auth flow and client ID, brings me to the expected Cognito page, where I can log in successfully. The dev environment also worked for me, so I think this is environment-specific configuration.

cc: @botanical @anayeaye

**Comment by botanical** [comment]
Thanks, @ividito! I added the correct callback url to cognito app client, so it should work now.

**Comment by anayeaye** [comment]
This was resolved with the callback url update
