### ISSUE TITLE
Event Driven Ingest of daily datasets 

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data-airflow#19]
The fireline researchers are storing updated datasets in s3 multiple times a day. These updates will need to be ingested using airflow by triggering the discover dag. AWS Event Bridge can be used to facility these events. 

**Acceptance Criteria**

- [ ] Uploading a file to S3 triggers the discover DAG

**Comment by j08lue** [comment]
This is a mechanism that is very interesting for other regularly updated (raster data) collections, like GEOGLAM https://github.com/NASA-IMPACT/veda-data-pipelines/issues/202
