### ISSUE TITLE
Necessary values are propagated from veda-data-airflow to veda-routes repo for CloudFront distribution origin management

### ISSUE THREAD

**Issue by botanical** [NASA-IMPACT/veda-data-airflow#195]
## Context

- Epic Link: https://github.com/NASA-IMPACT/veda-architecture/issues/469
- ADR: https://github.com/NASA-IMPACT/veda-architecture/pull/464

Propagate the necessary values for CloudFront distribution origin management 
- [workflows api ](https://github.com/NASA-IMPACT/veda-data-airflow/blob/dev/infrastructure/outputs.tf#L13-L15)

## Acceptance Criteria

- [x] API Gateway value for workflows API is propagated to veda-routes

**Comment by ciaransweet** [comment]
@botanical I think: `.github/actions/terraform-deploy/action.yml:72` does this? 

Or at least, this issue is probably more relevant to being done in `veda-deploy`?

As the output is defined in `infrastructure/outputs.tf:13`

**Comment by ciaransweet** [comment]
I also don't suppose you have an example of that json file? 😇

**Comment by ciaransweet** [comment]
Closing as it was completed in https://github.com/NASA-IMPACT/veda-deploy/pull/38
