### ISSUE TITLE
Review and test DAGs in dev SM2A

### ISSUE THREAD

**Issue by smohiudd** [NASA-IMPACT/veda-data-airflow#233]
## Description

Dev SM2A is deployed https://sm2a.dev.openveda.cloud/. Here is an outline of testing required:

- Test ingestion for raster and vector dataset in dev catalog
- Verify DAG logging and monitoring in dev SM2A

## Acceptance Criteria 
- Tests for dev SM2A documented in this ticket

**Comment by anayeaye** [comment]
We can do this testing in smce-staging now, too.

Here are some outdated notes on testing ingests via MWAA that could be adapted to develop our SM2A test suite: https://github.com/NASA-IMPACT/veda-data-airflow/issues/184

**Comment by smohiudd** [comment]
I just tried the transfer DAG in SM2A staging using this config and it didn't work:
```
{
    "origin_bucket": "veda-data-store-staging",
    "origin_prefix": "2024tornadoes/",
    "target_bucket": "veda-data-store",
    "collection": "tornadoes-2024-polygons",
    "filename_regex": "(.*)Tornado_Polygons_(.*).tif$"
}
```
I tried a similar config in MWAA staging and it worked

**Comment by anayeaye** [comment]
I ran a couple of the new dataset-config JSON files through dev.sm2a from [this big batch of promotions](https://github.com/NASA-IMPACT/veda-data/issues/187) and they worked as expected
