### ISSUE TITLE
Bug: Deployment doesn't push latest changes in the ecs tasks

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-data-airflow#72]
# Description
The ecs tasks (eg: build_stac) image is only updated on deployment if there are changes in the Dockerfile or handler.py, which isn't necessarily correct because there are dependencies on other files too. 

This is a limitation in the base terraform module used since the triggers are only those two files.

**Comment by amarouane-ABDELHAK** [comment]
A [PR](https://github.com/NASA-IMPACT/veda-data-airflow/pull/77) was issued to fix this problem, the new base terraform module release [v1.1.4](https://github.com/NASA-IMPACT/mwaa_tf_module/releases/download/v1.1.4/mwaa_tf_module.zip)  implements the functionality that automatically triggers the building of a Docker image and pushes it to the Amazon Elastic Container Registry (ECR) whenever a file within an ECS task folder is modified.
We are still supporting the explicit trigger if handler.py or Dockerfile changed, this is deprecated and will be removed in the future release
