### ISSUE TITLE
Pass discovery output to next step via s3

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-data-airflow#98]
# Motivation
The max size of the payload that can be passed between states in a step function is 256KB. Sometimes, when the number of items discovered is too many (`s3-discovery` lambda), the payload size exceeds the threshold and results in the cancellation of the state machine.

# Workaround
The workaround we've been using up until now is using the `filename_regex` key to divide the total items to chunks and running separate workflows for each chunk.
Eg:
```json
    {
        "collection": "co2-diff",
        "prefix": "co2-diff/",
        "bucket": "veda-data-store-staging",
        "filename_regex": "^(.*)2015.*.tif$",
        "discovery": "s3"
    },
    {
        "collection": "co2-diff",
        "prefix": "co2-diff/",
        "bucket": "veda-data-store-staging",
        "filename_regex": "^(.*)2016.*.tif$",
        "discovery": "s3"
    },
``` 
instead of 
```json
    {
        "collection": "co2-diff",
        "prefix": "co2-diff/",
        "bucket": "veda-data-store-staging",
        "filename_regex": "^*.tif$",
        "discovery": "s3"
    },
```

# Solution
Rather than passing the payload directly to another state, we could write the payload to an s3 bucket, pass only the URL of the object and the next state would read the object from the s3 bucket.

**Comment by ividito** [comment]
This should be less of an issue now, but still worth considering for refactors. In the new Airflow pipeline, the max XCOM size is 1 GB. I don't think we've run into this issue since making the switch.

**Comment by slesaad** [comment]
in airflow, the payload to the next step is passed via a file in s3 already!
